import { EditorView } from '@codemirror/view';

export const autocompleteTheme = EditorView.theme({
  '.cm-tooltip': {
    zIndex: '99999 !important',
  },
  '.cm-tooltip-autocomplete': {
    minWidth: '280px',
    maxWidth: '460px',
    zIndex: '99999 !important',
    background: 'var(--token-bg-surface) !important',
    border: '1px solid color-mix(in srgb, var(--token-accent-base) 70%, transparent) !important',
    borderRadius: '10px',
    boxShadow: '0 18px 40px color-mix(in srgb, var(--token-bg-app) 42%, transparent)',
    overflow: 'hidden',
  },
  '.cm-tooltip-autocomplete ul': {
    maxHeight: '320px',
    padding: '4px 0',
    margin: '0',
    listStyle: 'none',
  },
  '.cm-tooltip-autocomplete li': {
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    minHeight: '50px',
    padding: '8px 12px !important',
    color: 'var(--token-text-secondary) !important',
  },
  '.cm-tooltip-autocomplete li[aria-selected]': {
    backgroundColor: 'var(--token-accent-base) !important',
    color: 'var(--token-text-primary) !important',
  },
  '.cm-completionLabel': {
    flex: '1',
    minWidth: '0',
    display: 'flex',
    alignItems: 'center',
    fontWeight: '500',
    minHeight: '34px',
    lineHeight: '1.35',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  '.cm-completionDetail': {
    color: 'var(--token-text-muted)',
    marginLeft: 'auto',
    flex: '0 0 auto',
    alignSelf: 'center',
    fontSize: '11px',
    borderRadius: '999px',
    padding: '2px 8px',
    background: 'color-mix(in srgb, var(--token-overlay-on-bg) 75%, transparent)',
  },
  '.cm-tooltip-autocomplete li[aria-selected] .cm-completionDetail': {
    color: 'var(--token-text-primary)',
    background: 'color-mix(in srgb, var(--token-overlay-on-bg) 100%, transparent)',
  },
  '.cm-tooltip.cm-completionInfo': {
    zIndex: '100000 !important',
    padding: '0',
    border: '1px solid color-mix(in srgb, var(--token-accent-base) 55%, transparent)',
    borderRadius: '14px',
    background: 'color-mix(in srgb, var(--token-bg-app) 98%, transparent)',
    boxShadow: '0 24px 48px color-mix(in srgb, var(--token-bg-app) 42%, transparent)',
    overflow: 'hidden',
  },
  '.linghuiCompletionLeading': {
    display: 'inline-flex',
    alignItems: 'center',
    flex: '0 0 auto',
  },
  '.linghuiCompletionThumb': {
    position: 'relative',
    width: '34px',
    height: '34px',
    borderRadius: '10px',
    overflow: 'hidden',
    background: 'color-mix(in srgb, var(--token-bg-hover) 88%, transparent)',
    border: '1px solid color-mix(in srgb, var(--token-text-tertiary) 22%, transparent)',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: 'var(--token-text-secondary)',
    fontSize: '11px',
    fontWeight: '700',
  },
  '.linghuiCompletionThumbImage': {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  '.linghuiCompletionThumbBadge': {
    position: 'absolute',
    right: '3px',
    bottom: '2px',
    fontSize: '10px',
    lineHeight: '1',
    color: 'var(--token-text-primary)',
    textShadow: '0 1px 3px color-mix(in srgb, var(--token-bg-app) 60%, transparent)',
  },
  '.linghuiCompletionKindBadge': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: '34px',
    height: '34px',
    padding: '0 8px',
    borderRadius: '10px',
    background: 'color-mix(in srgb, var(--token-bg-card) 82%, transparent)',
    border: '1px solid color-mix(in srgb, var(--token-text-tertiary) 22%, transparent)',
    color: 'var(--token-text-secondary)',
    fontSize: '11px',
    fontWeight: '700',
  },
  '.linghuiCompletionInfoCard': {
    width: '240px',
    padding: '10px',
    color: 'var(--token-text-secondary)',
  },
  '.linghuiCompletionInfoImageWrap': {
    position: 'relative',
    width: '100%',
    height: '144px',
    borderRadius: '10px',
    overflow: 'hidden',
    background: 'color-mix(in srgb, var(--token-bg-card) 90%, transparent)',
  },
  '.linghuiCompletionInfoImage': {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  '.linghuiCompletionInfoVideoBadge': {
    position: 'absolute',
    top: '8px',
    right: '8px',
    padding: '2px 6px',
    borderRadius: '999px',
    background: 'color-mix(in srgb, var(--token-bg-card) 80%, transparent)',
    color: 'var(--token-text-primary)',
    fontSize: '10px',
    fontWeight: '700',
    letterSpacing: '0.04em',
  },
  '.linghuiCompletionInfoTitle': {
    marginTop: '8px',
    fontSize: '13px',
    fontWeight: '700',
    color: 'var(--token-text-primary)',
  },
  '.linghuiCompletionInfoMeta': {
    marginTop: '4px',
    color: 'color-mix(in srgb, var(--token-accent-base) 66%, var(--token-text-primary))',
    fontSize: '11px',
    fontWeight: '700',
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
  },
  '.linghuiCompletionInfoDescription': {
    marginTop: '6px',
    color: 'var(--token-text-tertiary)',
    fontSize: '12px',
    lineHeight: '1.5',
  },
});
